export const GUIDELINES = [
  {
    org: "ASCIA",
    full: "Australasian Society of Clinical Immunology and Allergy",
    url: "https://www.allergy.org.au",
    color: "#7B3348",
    bg: "#FAEAEE",
    rules: [
      "Use fragrance-free products on all babies with eczema or sensitive skin",
      "Avoid products containing food-derived ingredients (e.g. oat, milk, nut oils) on infants who have not yet been introduced to solids",
      "Introduce common food allergens (egg, peanut, cow's milk, wheat, soy, sesame, fish) before 12 months",
      "Prefer emollients with simple, short ingredient lists for eczema management",
      "Avoid lanolin-based products in infants with suspected wool sensitivity",
    ],
  },
  {
    org: "NAC",
    full: "National Allergy Council",
    url: "https://nationalallergycouncil.org.au",
    color: "#3D8F6A",
    bg: "#EAF5EF",
    rules: [
      "Implement the National Allergy Strategy to reduce allergy burden in Australia",
      "Recommend early introduction of allergenic foods to reduce food allergy risk",
      "Support parents to identify safe products aligned with clinical evidence",
      "Encourage collaboration between ASCIA and Allergy & Anaphylaxis Australia (A&AA)",
    ],
  },
  {
    org: "A&AA",
    full: "Allergy & Anaphylaxis Australia",
    url: "https://allergyfacts.org.au",
    color: "#A96E28",
    bg: "#FEF5E6",
    rules: [
      "Always read ingredient labels — allergens may hide under chemical names",
      "Be aware that 'natural' or 'organic' does not mean allergen-free",
      "Food derivatives in skincare (oat, almond, wheat) can sensitise infants via skin exposure",
      "Seek medical advice before using new products on babies with known food allergies",
    ],
  },
  {
    org: "FSANZ",
    full: "Food Standards Australia New Zealand",
    url: "https://www.foodstandards.gov.au",
    color: "#4A6FA5",
    bg: "#EDF3FA",
    rules: [
      "Mandates declaration of 9 allergens on all packaged food: peanut, tree nuts, milk, eggs, sesame, fish, crustaceans, soy, gluten-containing cereals",
      "Requires bold allergen declaration on all food packaging in Australia",
      "Governs precautionary labelling ('may contain') to inform allergy families",
    ],
  },
  {
    org: "NACE",
    full: "National Allergy Centre of Excellence",
    url: "https://www.nace.org.au",
    color: "#6B4BA8",
    bg: "#F0EAFA",
    rules: [
      "Australia has one of the highest rates of childhood food allergy globally — 1 in 10 babies",
      "Eczema in early infancy significantly increases food allergy risk",
      "Early skin barrier protection (emollients, fragrance-free products) may reduce allergy development",
      "Ongoing research into prevention, diagnosis and treatment of childhood allergic disease",
    ],
  },
  {
    org: "Prevent Allergies",
    full: "Nip Allergies in the Bub Program",
    url: "https://preventallergies.org.au",
    color: "#3D8F6A",
    bg: "#EAF5EF",
    rules: [
      "Good eczema management in early infancy can reduce the risk of developing food allergy",
      "Apply moisturiser daily to keep the skin barrier intact",
      "Use prescribed eczema treatments promptly during flare-ups",
      "Introduce common food allergens by 12 months of age, even for high-risk babies",
    ],
  },
];
